# Generated by Django 4.0.5 on 2023-01-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empapp', '0007_remove_department_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_name', models.CharField(max_length=255, null=True)),
                ('Company_name', models.CharField(max_length=255, null=True)),
                ('Company_address', models.CharField(max_length=255, null=True)),
                ('Company_contact', models.CharField(max_length=255, null=True)),
                ('Company_email', models.EmailField(max_length=255, null=True)),
                ('Company_website', models.URLField(max_length=255, null=True)),
                ('Service_opted', models.CharField(max_length=255, null=True)),
                ('Service_status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
